// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://qsxsemmpsyqebrnpnnhe.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzeHNlbW1wc3lxZWJybnBubmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzMDkyNDEsImV4cCI6MjA0ODg4NTI0MX0.EKMIO4GmXhCIV9qlVh31XHDRoE3365xOP0BQUm6OYcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);